<?php

namespace App\Services;

use App\Models\OrderPayment;
use Barryvdh\DomPDF\Facade\Pdf;

class InvoicePdfService
{
    public function __construct(private QrService $qr) {}

    public function download(OrderPayment $payment): \Symfony\Component\HttpFoundation\Response
    {
        $html = $this->buildHtml($payment);
        return Pdf::loadHTML($html)->setPaper('a4', 'portrait')->download($payment->invoice_number . '.pdf');
    }

    public function stream(OrderPayment $payment): \Symfony\Component\HttpFoundation\Response
    {
        $html = $this->buildHtml($payment);
        return Pdf::loadHTML($html)->setPaper('a4', 'portrait')->stream($payment->invoice_number . '.pdf');
    }

    private function buildHtml(OrderPayment $payment): string
    {
        $order      = $payment->order;
        $cfg        = config('payment');
        $amountFmt  = $payment->amountFormatted();
        $totalFmt   = $payment->currency === 'IDR'
            ? 'Rp ' . number_format($order->final_price, 0, ',', '.')
            : '$' . number_format($order->final_price, 2);

        $logoPath   = public_path('IMG/Rielcode Logo Square Transparent.svg');
        $logoTag    = file_exists($logoPath)
            ? '<div style="font-size:22px;font-weight:bold;color:#2d4a3a;">Rielcode</div>'
            : '<div style="font-size:22px;font-weight:bold;color:#2d4a3a;">Rielcode</div>';

        $paymentSection = $payment->currency === 'IDR' ? $this->idrSection($cfg) : $this->usdSection($cfg, $payment);

        return <<<HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; margin: 40px; }
  .header-table { width: 100%; margin-bottom: 30px; }
  .right { text-align: right; }
  .label { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #888; margin-bottom: 6px; }
  .stage-banner { background: #eef7f0; border: 1px solid #a8d5b5; color: #1a3d2a; padding: 10px 14px; border-radius: 6px; margin-bottom: 20px; font-size: 11px; }
  .meta-table { width: 100%; margin-bottom: 20px; }
  .meta-table td { padding: 4px 0; vertical-align: top; }
  .project-box { background: #f9f9f9; border: 1px solid #eee; border-radius: 6px; padding: 14px; margin-bottom: 20px; }
  .total-box { background: #f0f7f2; border: 1px solid #a8d5b5; border-radius: 8px; padding: 20px; text-align: center; margin-bottom: 24px; }
  .total-amount { font-size: 22px; font-weight: bold; color: #2d4a3a; }
  .bank-box { background: #fafafa; border: 1px solid #eee; border-radius: 6px; padding: 16px; }
  .bank-row { padding: 6px 0; border-bottom: 1px solid #eee; }
  .bank-row:last-child { border-bottom: none; }
  .bank-k { color: #777; font-size: 11px; }
  .bank-v { font-weight: bold; }
  .footer { margin-top: 40px; font-size: 10px; color: #aaa; text-align: center; }
</style>
</head>
<body>
<table class="header-table"><tr>
  <td>{$logoTag}<div style="color:#888;font-size:11px;">rielcode.com</div></td>
  <td class="right">
    <div style="color:#888;font-size:11px;">Invoice</div>
    <div style="font-weight:bold;font-size:13px;">{$payment->invoice_number}</div>
    <div style="color:#888;font-size:11px;">Due: {$payment->due_date->format('d M Y')}</div>
    <div style="color:#888;font-size:11px;">Status: {$payment->status}</div>
  </td>
</tr></table>

<div class="stage-banner"><strong>{$payment->stageLabel()}</strong> &mdash; {$payment->stageTagline()}</div>

<table class="meta-table"><tr>
  <td>
    <div class="label">Bill To</div>
    <strong>{$order->order_name}</strong><br>
    <span style="color:#555;">{$order->email}</span>
  </td>
  <td class="right">
    <div class="label">Currency</div>
    <strong>{$payment->currency}</strong>
  </td>
</tr></table>

<div class="project-box">
  <div class="label">Project</div>
  <strong>{$order->package}</strong>
  <div style="border-top:1px solid #eee;margin-top:10px;padding-top:10px;color:#777;font-size:11px;">
    Total project value: <strong style="color:#1a1a1a;">{$totalFmt}</strong>
  </div>
</div>

<div class="total-box">
  <div class="label">Amount Due ({$payment->stageLabel()})</div>
  <div class="total-amount">{$amountFmt}</div>
</div>

{$paymentSection}

<div style="color:#777;font-size:10px;margin-top:14px;">After payment, send proof via WhatsApp to confirm. The invoice will then be marked Paid.</div>

<div class="footer">Generated by Rielcode &mdash; rielcode.com</div>
</body>
</html>
HTML;
    }

    private function idrSection(array $cfg): string
    {
        return <<<HTML
<div class="bank-box">
  <div class="label">Payment &mdash; QRIS or Bank Transfer (Indonesia)</div>
  <div style="color:#555;font-size:10px;margin-bottom:10px;">Transfer to:</div>
  <div class="bank-row"><span class="bank-k">Bank Name</span><br><span class="bank-v">{$cfg['bank_name']}</span></div>
  <div class="bank-row"><span class="bank-k">Account Number</span><br><span class="bank-v" style="font-size:14px;letter-spacing:1px;">{$cfg['bank_number']}</span></div>
  <div class="bank-row"><span class="bank-k">Account Name</span><br><span class="bank-v">{$cfg['bank_name_account']}</span></div>
</div>
HTML;
    }

    private function usdSection(array $cfg, OrderPayment $payment): string
    {
        $intl = $cfg['intl'];
        $intermediary = $intl['intermediary_bank']
            ? "<div class=\"bank-row\"><span class=\"bank-k\">Intermediary Bank</span><br><span class=\"bank-v\">{$intl['intermediary_bank']}</span></div>
               <div class=\"bank-row\"><span class=\"bank-k\">Intermediary SWIFT</span><br><span class=\"bank-v\">{$intl['intermediary_swift']}</span></div>"
            : '';

        return <<<HTML
<div class="bank-box">
  <div class="label">Payment &mdash; International Wire Transfer (SWIFT)</div>
  <div class="bank-row"><span class="bank-k">Beneficiary Name</span><br><span class="bank-v">{$intl['beneficiary_name']}</span></div>
  <div class="bank-row"><span class="bank-k">Beneficiary Address</span><br><span class="bank-v">{$intl['beneficiary_address']}</span></div>
  <div class="bank-row"><span class="bank-k">Bank Name</span><br><span class="bank-v">{$intl['bank_name']}</span></div>
  <div class="bank-row"><span class="bank-k">Bank Address</span><br><span class="bank-v">{$intl['bank_address']}</span></div>
  <div class="bank-row"><span class="bank-k">Account Number / IBAN</span><br><span class="bank-v">{$intl['account_number']}</span></div>
  <div class="bank-row"><span class="bank-k">SWIFT / BIC</span><br><span class="bank-v">{$intl['swift_code']}</span></div>
  {$intermediary}
  <div style="color:#777;font-size:10px;margin-top:10px;">Wire fees borne by sender. Reference invoice number ({$payment->invoice_number}) in the wire message field.</div>
</div>
HTML;
    }
}
